FROM python:3.11-slim as base

ENV DEV=${DEV:-0}
ENV PYDEVD_DISABLE_FILE_VALIDATION=1
ENV PYTHONUNBUFFERED=1 \
  PYTHONDONTWRITEBYTECODE=1 \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    g++ \
    curl \
    # Required for scientific and mathematical libraries, such as numpy and pandas
    gfortran \
    libopenblas-dev \
    openssl \
    && rm -rf /var/lib/apt/lists/*

# Install uv
RUN pip install uv

# Copy the project into the image
ADD . /app

# Set the working directory
WORKDIR /app

# Create a virtual environment
RUN uv venv /opt/venv

# Use the virtual environment automatically
ENV VIRTUAL_ENV=/opt/venv

# Place entry points in the environment at the front of the path
ENV PATH="/opt/venv/bin:$PATH"

# Copy pyproject.toml for dependency installation
COPY pyproject.toml .

# Install the project dependencies using uv
RUN uv pip install -r pyproject.toml

# Expose debugging port
EXPOSE 5678

# Expose application port
EXPOSE 8000

# Run the application with hot reloading
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
