services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5555:8000"
    volumes:
      - .:/app
      - /app/__pycache__/
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
