[project]
name = "snakesss"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb",
    "langchain-chroma>=0.1.2",
    "langchain-community>=0.2.16",
    "langchain-openai>=0.1.23",
    "langchain>=0.2.16",
    "langgraph>=0.2.19",
    "openai",
    "pip>=24.3.1",
    "pre-commit>=3.8.0",
    "pydantic-settings>=2.5.2",
    "pytest>=8.3.3",
    "python-dotenv",
    "python-multipart>=0.0.17",
    "pytz>=2024.2",
    "ruff>=0.6.4",
    "spacy>=3.7.5",
    "tqdm>=4.64.1",
    "typer>=0.12.5",
    "uvicorn",
]

[tool.hatch.build.targets.wheel]
packages = ["main.py"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
venvPath = "."
venv = ".venv"
exclude = [
    "**/__pycache__", # cache directories
    "./typings",      # generated type stubs
]
stubPath = "./typings"

[tool.ruff]
line-length = 110
target-version = "py310"
extend-exclude = ["/usr/lib/*"]

[tool.ruff.lint]
ignore = [
    "E501", # line too long - will be fixed in format
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
docstring-code-format = true
exclude = [
    "src/flux/_version.py", # generated by setuptools_scm
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-wrap-aliases = true
known-local-folder = ["src"]
known-first-party = ["flux"]
