[project]
name = "snakesss"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "groq>=0.9.0",
    "strawberry-graphql[fastapi]",
    "supabase",
    "uvicorn",
    "python-dotenv",
    "openai",
    "chromadb",
    "pillow",
    "torch",
    "torchvision",
    "torchaudio",
    "transformers",
    "typer>=0.12.5",
    "anthropic>=0.34.1",
    "langchain>=0.2.16",
    "langchain-community>=0.2.16",
    "langchain-openai>=0.1.23",
    "tqdm>=4.64.1",
]

[tool.hatch.build.targets.wheel]
packages = ["main.py"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
venvPath = "."
venv = ".venv"
exclude = [
    "**/__pycache__", # cache directories
    "./typings",      # generated type stubs
]
stubPath = "./typings"

[tool.ruff]
line-length = 110
target-version = "py310"
extend-exclude = ["/usr/lib/*"]

[tool.ruff.lint]
ignore = [
    "E501", # line too long - will be fixed in format
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
docstring-code-format = true
exclude = [
    "src/flux/_version.py", # generated by setuptools_scm
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-wrap-aliases = true
known-local-folder = ["src"]
known-first-party = ["flux"]
