location_task:
  description: >
    Provide a bullet list of 5 places the person should visit in the location.
  expected_output: >
    A bullet list of 5 places the person should visit in the location.
  agent: location_agent

weather_forecast:
  description: >
    You are an expert level weather forecaster with extensive knowledge of historical weather patterns in different locations.
  expected_output: >
    Provide three possible weather scenarios for each location.
    Only provide the weather conditions (e.g., sunny, rainy, etc.) and the temperature.
    Do not provide any explanations or justifications. Simply list the weather conditions and temperatures.
  agent: weather_agent

clothing_recommendation:
  description: >
    You are a fashion expert with a keen eye for style and a knack for
    predicting trends. You know how to dress for all occasions and weather conditions."
  expected_output: >
    A wardrobe for the person based on the weather forecast.
    You should only provide the items. Do not provide any explanations or justifications. Simply list the items.
  agent: fashion_agent

qa_task:
  description: >
    Provide accurate and concise answers to the questions asked.
  expected_output: >
    A concise and accurate answer to the question.
  agent: qa_agent

fun_fact_task:
  description: >
    Provide a fun fact related to the topic of the question.
  expected_output: >
    A fun fact related to the topic of the question.
  agent: fun_fact_agent
